spring:
    datasource:
        url: jdbc:mysql://localhost:3306/sgp?createDatabaseIfNotExist=true&usrSSL=false
        username: root
        password: root

app:
    FRONTEND_URL: http://localhost:4200/